version: '3'
services:
  dispatcher:
    build:
      context: .
    image: dispathcer 
    ports:
      - "5555:5555"
    tty: true
    privileged: true
    network_mode: "host"
    volumes:
     - /lib/modules:/lib/modules
